openapi: 3.0.0
info:
  title: API-Service
  version: '1.0'
  description: Describe the recolector service
servers:
  - url: 'http://localhost:80'
    description: Local
paths:
  /api/v1/register:
    post:
      summary: Register a email
      operationId: post-api-v1-register
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
              required:
                - email
        description: ''
      description: ''
  /api/v1/gatherer:
    post:
      summary: Push date
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  message:
                    type: string
                    minLength: 1
                required:
                  - message
              examples:
                example-1:
                  value:
                    message: success
      operationId: post-api-v1-gatherer
      security:
        - API Key: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                timestamp:
                  type: string
                  format: date-time
                latitude:
                  type: number
                  format: double
                longitude:
                  type: number
                  format: double
                dba:
                  type: string
  /api/v1/auth:
    post:
      summary: Authorize
      operationId: post-api-v1-auth
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    description: token JWT signed
                required:
                  - token
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
              required:
                - email
components:
  schemas: {}
  securitySchemes:
    API Key:
      name: x-access-token
      type: apiKey
      in: header
      description: ''
